"""
Django settings for pyfic project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

DEBUG = True

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django_extensions',
    'faker_meta_db'
]

DATABASES = {
    'SCHEMA1': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA1"'
        }
    },
    'SCHEMA2': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA2"'
        }
    },
    'SCHEMA3': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA3"'
        }
    }, 
    'SCHEMA4': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA4"'
        }
    },
    'SCHEMA5': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA5"'
        }
    }, 
    'SCHEMA6': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA6"'
        }
    }, 
    'SCHEMA7': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA7"'
        }
    },
    'SCHEMA8': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA8"'
        }
    },
    'SCHEMA9': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA9"'
        }
    },
    'SCHEMA10': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'homelab',
        'PASSWORD': 'tQ_EH&oyk9U<YX*2',
        'HOST': 'database',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path="SCHEMA10"'
        }
    },
    'default': {
    }
}


